version = 1

# Intended for use within Piskel fork at git@github.com:rossturk/piskel.git
#
# The fork contains an updated version of nwjs

[install]
nodejs.pkg-path = "nodejs"

[build]
piskel.version = "2025050701"
piskel.description = "A simple web-based tool for Spriting and Pixel art."
piskel.command = '''
npm install --omit=dev
npm install grunt-cli --save-dev

if [[ $(uname) == 'Darwin' ]]; then
  node_modules/.bin/grunt desktop-mac
  cp -r out/ $out/
  mkdir -p $out/Applications
  mv $out/piskel.app $out/Applications/piskel.app
else
  node_modules/.bin/grunt desktop

  mkdir -p $out/piskel
  cp -r out/* $out/piskel/

  mkdir -p $out/bin
  mv $out/piskel/piskel $out/bin/piskel

  mv $out/piskel/lib $out/
fi
'''
